project_id = "brdrkhgfbbrgdkzdfbpr"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.whatsapp-fallback]
verify_jwt = false

[functions.send-appointment-whatsapp]
verify_jwt = false

[functions.send-invoice-whatsapp]
verify_jwt = false